### ISSUE TITLE
域名转发无法使用

### ISSUE THREAD

**Issue by fi6** [lmc999/TinyPortMapper_KeepAlive#1]
请输入本地监听端口:1935
请输入远端转发端口:1935
请输入被转发域名:txy.live-send.acg.tv

 ps -aux | grep tinymapper
fi****        **** 0.0  0.5 112744  2408 pts/0    S+   12:58   0:00 grep --color=auto tinymapper
然后并没有产生record.txt文件

**Comment by lmc999** [comment]
看一下tinymapper的log看看是不是端口占用了

**Comment by poly-1** [comment]
> 请输入本地监听端口:1935
> 请输入远端转发端口:1935
> 请输入被转发域名:txy.live-send.acg.tv
> 
> ps -aux | grep tinymapper
> fi**** **** 0.0 0.5 112744 2408 pts/0 S+ 12:58 0:00 grep --color=auto tinymapper
> 然后并没有产生record.txt文件

推荐使用一个修改版 [https://github.com/ss-daily-backup/TinyPortMapper_DDNS](https://github.com/ss-daily-backup/TinyPortMapper_DDNS)

**Comment by lmc999** [comment]
> 请输入本地监听端口:1935
> 请输入远端转发端口:1935
> 请输入被转发域名:txy.live-send.acg.tv
> 
> ps -aux | grep tinymapper
> fi**** **** 0.0 0.5 112744 2408 pts/0 S+ 12:58 0:00 grep --color=auto tinymapper
> 然后并没有产生record.txt文件

脚本本身设计是用来转发VPS流量的，而你用来转发的是CDN域名而且有多个解析记录，建议你手动修改脚本选取其中一个解析出来的IP
